[package]
name = "baseball"
version = "0.1.0"
edition = "2021"
author = ["Peter <rustengineer@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
